name: dread
description: Generates contracts for rebel server/client and body transformer
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: any
  code_builder: any
  dart_style: any

dev_dependencies:
  test: ^0.12.0

executables:
  dread: main
